# Generated by Django 6.1 on 2026-09-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('avatar', models.ImageField(upload_to='films')),
            ],
        ),
    ]
