# Generated by Django 6.1 on 2026-09-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_genre_delete_films_film_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='avatar',
            new_name='poster',
        ),
    ]
