# Generated by Django 6.1 on 2026-09-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_remove_film_genre_film_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='genre',
            new_name='genres',
        ),
    ]
